import requests


# Enter your authentication credentials
access_token = 'eyJ0eXAiOiJKV1QiLCJub25jZSI6InlXN2VqZm55aXRwc0F2eFo3NVpVODdlMDlxbXhOaVQ4S3N3SWFtcVAwZmMiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84NTgwNjQ5Mi0wNTFhLTQ2OTgtYTI2ZS1kNTZiZGE2MjkzMDEvIiwiaWF0IjoxNjc5ODk5OTgzLCJuYmYiOjE2Nzk4OTk5ODMsImV4cCI6MTY3OTk4NjY4MywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQTBsSWlSZEU2M2l0b2RQNmhDb2xqZkFJZFdUZWNVdjhVZUJVL0RsYmJrOTRVczFXMEpOdXhWdGNGNHhkN1I3bWc5VVZqVWJMWnJoYytIU1FMSm1rZksvU2ZSdzU1N0dMZXZKV3BxRk5wZ0xNPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiR3JhcGggRXhwbG9yZXIiLCJhcHBpZCI6ImRlOGJjOGI1LWQ5ZjktNDhiMS1hOGFkLWI3NDhkYTcyNTA2NCIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiUHJhc2FkIFNhbmFib2luYSIsImdpdmVuX25hbWUiOiJSYXZpIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTAzLjgxLjc4LjEwIiwibmFtZSI6IlJhdmkgUHJhc2FkIFNhbmFib2luYSIsIm9pZCI6IjU3NTg1ZDA5LTYwYWEtNDE3Mi04NDdiLWJiM2ViM2IyZTVjNCIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMjVCMEU1NEZEIiwicmgiOiIwLkFWWUFrbVNBaFJvRm1FYWlidFZyMm1LVEFRTUFBQUFBQUFBQXdBQUFBQUFBQUFDZkFNWS4iLCJzY3AiOiJBUElDb25uZWN0b3JzLlJlYWQuQWxsIEFQSUNvbm5lY3RvcnMuUmVhZFdyaXRlLkFsbCBDb250YWN0cy5SZWFkIENvbnRhY3RzLlJlYWQuU2hhcmVkIENvbnRhY3RzLlJlYWRXcml0ZSBDb250YWN0cy5SZWFkV3JpdGUuU2hhcmVkIERpcmVjdG9yeS5SZWFkLkFsbCBvcGVuaWQgT3JnQ29udGFjdC5SZWFkLkFsbCBQZW9wbGUuUmVhZC5BbGwgcHJvZmlsZSBVc2VyLlJlYWQgVXNlci5SZWFkV3JpdGUuQWxsIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiOVdKX3RYcTZJakFDZHV2Z1RNYlZMQVlRb3didjNZclRPVC1Jd2F1TnJNayIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6Ijg1ODA2NDkyLTA1MWEtNDY5OC1hMjZlLWQ1NmJkYTYyOTMwMSIsInVuaXF1ZV9uYW1lIjoicmF2aXByYXNhZDI1NDVAdjdocjgub25taWNyb3NvZnQuY29tIiwidXBuIjoicmF2aXByYXNhZDI1NDVAdjdocjgub25taWNyb3NvZnQuY29tIiwidXRpIjoiRTJiVFNPTXpxVUdGR1dDU0FBaHdBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19jYyI6WyJDUDEiXSwieG1zX3NzbSI6IjEiLCJ4bXNfc3QiOnsic3ViIjoiZjRQM29ZaEE4c0ttYlBoeFV0dDVxYkVHaEEwSndMVXdLZHJoRVBsYm5XcyJ9LCJ4bXNfdGNkdCI6MTY3MTI1NzAxNH0.q5C4G2EpwN9cJR03AXSNYlI0W-OQNt_fBEuNB1bYbqqWHR054pqYGc9TOBN9ZjFWKEf7Vln63kv-wIEZIwWiDC1MrGPI2faYsKVXuM6lGJSgyMIYDSKjkBo_kEqyygS9r96QIDa8yqVF9wLgGKpbrL6ZeSmJGpjh4ag8JHTQkLDeKE8Bp89yOeuRI8MX3ILqSc2T55Rwfn_HNAJ2ZqKPYyENm63M_iv8ZVTim58wNR464kPkAPB0Hw9yCuTXJ0fh7jwH4F1AtdgiaOt3rd1Yzz3eUiAc_lvU0lKPX7LiYck_sYuvEy18VYYvXdlpKZaZPBeGHnipjqK5pSshbtpWjw'



# Set the API endpoint and headers
url = 'https://graph.microsoft.com/v1.0/contacts'
headers = {
 'Authorization': 'Bearer ' + access_token,
'Content-Type': 'application/json'
}



# Set the contact details
contact = {
 'givenName': 'John',
 'surname': 'Doe',
 'emailAddresses': [
 {
 'address': 'john.doe@example.com',
 'name': 'John Doe'
}
 ]
}



# Make the API call to add the contact
response = requests.post(url, headers=headers, json=contact)



# Check the response status code
if response.status_code == 201:
 print('Contact added successfully!')
else:
 print('Error adding contact: ' + response.text)